/**
 * IR Homepage Scapes — Aurora Borealis (Northern Lights) Engine
  * engine/aurora.js
   *
    * Full GLSL shader-based aurora with:
     *  - Multi-band ribbons of flowing light
      *  - Real-time animated wave distortion
       *  - Color cycling through greens, teals, purples, pinks
        *  - Translucent layered glow
         *
          * Re-codeable: adjust BAND_COUNT, colors, wave speeds, intensity here.
           */

           IRScapes.Aurora = (function () {

             // GLSL Vertex Shader
               const vertexShader = `
                   uniform float uTime;
                       uniform float uWaveAmp;
                           uniform float uWaveFreq;
                               varying vec2 vUv;
                                   varying float vElevation;

                                       void main() {
                                             vUv = uv;
                                                   vec3 pos = position;
                                                         // Undulate the ribbon vertically
                                                               float wave = sin(pos.x * uWaveFreq + uTime * 0.8) * uWaveAmp
                                                                                + sin(pos.x * uWaveFreq * 0.4 + uTime * 0.5) * uWaveAmp * 0.6;
                                                                                      pos.y += wave;
                                                                                            vElevation = (pos.y + uWaveAmp) / (uWaveAmp * 2.0);
                                                                                                  gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
                                                                                                      }
                                                                                                        `;
                                                                                                        
                                                                                                          // GLSL Fragment Shader
                                                                                                            const fragmentShader = `
                                                                                                                uniform float uTime;
                                                                                                                    uniform vec3 uColor1;
                                                                                                                        uniform vec3 uColor2;
                                                                                                                            uniform vec3 uColor3;
                                                                                                                                uniform float uOpacity;
                                                                                                                                    varying vec2 vUv;
                                                                                                                                        varying float vElevation;
                                                                                                                                        
                                                                                                                                            float noise(vec2 p) {
                                                                                                                                                  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
                                                                                                                                                      }
                                                                                                                                                      
                                                                                                                                                          void main() {
                                                                                                                                                                // Fade at top and bottom edges
                                                                                                                                                                      float edgeFade = smoothstep(0.0, 0.18, vUv.y) * smoothstep(1.0, 0.82, vUv.y);
                                                                                                                                                                            // Horizontal shimmer
                                                                                                                                                                                  float shimmer = 0.5 + 0.5 * sin(vUv.x * 12.0 + uTime * 2.3);
                                                                                                                                                                                        float shimmer2 = 0.5 + 0.5 * sin(vUv.x * 5.0 - uTime * 1.1);
                                                                                                                                                                                        
                                                                                                                                                                                              // Color mix along the ribbon
                                                                                                                                                                                                    float t = vUv.x * 0.5 + uTime * 0.05;
                                                                                                                                                                                                          vec3 col = mix(uColor1, uColor2, sin(t) * 0.5 + 0.5);
                                                                                                                                                                                                                col = mix(col, uColor3, sin(t * 1.7 + 1.2) * 0.5 + 0.5);
                                                                                                                                                                                                                
                                                                                                                                                                                                                      // Brightness pulse
                                                                                                                                                                                                                            float brightness = 0.7 + 0.3 * shimmer * shimmer2;
                                                                                                                                                                                                                                  col *= brightness;
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                        float alpha = edgeFade * uOpacity * (0.6 + 0.4 * shimmer);
                                                                                                                                                                                                                                              gl_FragColor = vec4(col, alpha);
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                    `;
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                      function create(scene, options = {}) {
                                                                                                                                                                                                                                                          const {
                                                                                                                                                                                                                                                                bandCount = 5,
                                                                                                                                                                                                                                                                      baseY = 280,
                                                                                                                                                                                                                                                                            spreadY = 60,
                                                                                                                                                                                                                                                                                  width = 2000,
                                                                                                                                                                                                                                                                                        height = 120,
                                                                                                                                                                                                                                                                                              color1 = new THREE.Color(0x00ff88),
                                                                                                                                                                                                                                                                                                    color2 = new THREE.Color(0x00ccff),
                                                                                                                                                                                                                                                                                                          color3 = new THREE.Color(0xaa44ff),
                                                                                                                                                                                                                                                                                                                opacity = 0.55,
                                                                                                                                                                                                                                                                                                                      waveAmp = 30,
                                                                                                                                                                                                                                                                                                                            waveFreq = 0.008
                                                                                                                                                                                                                                                                                                                                } = options;
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                    const bands = [];
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        for (let i = 0; i < bandCount; i++) {
                                                                                                                                                                                                                                                                                                                                              const geo = new THREE.PlaneGeometry(width, height, 200, 20);
                                                                                                                                                                                                                                                                                                                                                    const mat = new THREE.ShaderMaterial({
                                                                                                                                                                                                                                                                                                                                                            vertexShader,
                                                                                                                                                                                                                                                                                                                                                                    fragmentShader,
                                                                                                                                                                                                                                                                                                                                                                            transparent: true,
                                                                                                                                                                                                                                                                                                                                                                                    depthWrite: false,
                                                                                                                                                                                                                                                                                                                                                                                            blending: THREE.AdditiveBlending,
                                                                                                                                                                                                                                                                                                                                                                                                    uniforms: {
                                                                                                                                                                                                                                                                                                                                                                                                              uTime:     { value: 0 },
                                                                                                                                                                                                                                                                                                                                                                                                                        uWaveAmp:  { value: waveAmp * (0.6 + Math.random() * 0.8) },
                                                                                                                                                                                                                                                                                                                                                                                                                                  uWaveFreq: { value: waveFreq * (0.7 + Math.random() * 0.6) },
                                                                                                                                                                                                                                                                                                                                                                                                                                            uColor1:   { value: color1.clone().multiplyScalar(0.8 + Math.random() * 0.4) },
                                                                                                                                                                                                                                                                                                                                                                                                                                                      uColor2:   { value: color2.clone().multiplyScalar(0.8 + Math.random() * 0.4) },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                uColor3:   { value: color3.clone().multiplyScalar(0.8 + Math.random() * 0.4) },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          uOpacity:  { value: opacity * (0.5 + Math.random() * 0.5) }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const mesh = new THREE.Mesh(geo, mat);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mesh.position.set(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            (Math.random() - 0.5) * 400,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    baseY + (i / bandCount) * spreadY + (Math.random() - 0.5) * 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -600 + (Math.random() - 0.5) * 200
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mesh.rotation.x = -0.1 + Math.random() * 0.2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              mesh.rotation.z = (Math.random() - 0.5) * 0.15;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mesh.userData.auroraOffset = Math.random() * Math.PI * 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          scene.add(mesh);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bands.push(mesh);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return bands;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function tick(bands, elapsed) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bands.forEach(band => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      band.material.uniforms.uTime.value = elapsed + band.userData.auroraOffset;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function dispose(bands, scene) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bands.forEach(band => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        band.geometry.dispose();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              band.material.dispose();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scene.remove(band);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { create, tick, dispose };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })();
